---
name: Terraform Validate and Format
on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]
permissions:
  contents: read
jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
      - name: Terraform Init
        run: terraform init -backend=false
        working-directory: .
      - name: Terraform Validate
        run: terraform validate
        working-directory: .
      - name: Terraform Format
        run: terraform fmt -check -recursive